### ISSUE TITLE
커밋 메시지 형식을 통일 하는것이 어떨까?

### ISSUE THREAD

**Issue by HyunGyu-Lee** [Team-HST/wwl#1]
지금 wwl에 커밋하는 경우는 크게 아래와 같습니다.

- 주간목표 (개인 디렉토리)
  - 차주 주간 목표 수립
  - 금주 주간 목표 진행상황 업데이트
- 스터디
  - 스터디 일정 변동사항 업데이트 (README.md)
  - 스터디 기록 추가 및 업데이트 (study-log)

지금 현재 커밋된 메시지들을 보면 다들 의미는 상통하나 문구가 조금 상이한 부분이 있는거 같습니다.

이를 위해 각 활동에 메시지를 통일하면 좋을 것 같다는 생각이 듭니다.

제안하는 형식은

```
[카테고리] 액션 - 상세내용

e.g.
[주간목표] 차주 주간목표 추가 (01-20) 
[주간목표] 진행상황 업데이트 - ~~~ 목표 완료
[스터디] 일정변경 - 차주 리뷰일 ~~로 변경
```

모든 커밋 메시지를 통일할 수는 없겠지만, 일반적인 경우에 대해서는 일관성을 가질수있다는 생각이듭니다. 
그리고, 메시지에 활동한 내역을 보다 상세히 적어 멤버 간 활동을 모니터링하고 더 정확한 피드백을 주는데에 도움이 될 것이라고 생각합니다.

**Comment by dudgns0612** [comment]
확인하였습니다.

**Comment by shl9012** [comment]
좋은 의견이네요.
공동으로 사용하는 팀 레파지토리 내에서는 메시지 형식을 통일하는 게 맞는 것 같습니다.
혹시 멤버 간 활동과 피드백을 위해 커밋타이틀 외에 내용까지 통일하고자 하는 건지 여쭤봅니다.
우선 해당 내용은 금주부터 적용하도록 개선하겠습니다. 감사합니다.

**Comment by hanull** [comment]
> 확인하였습니다.

더 길게 써주세요

**Comment by hanull** [comment]
좋은 생각이군요. 구체적인 형식을 예시로 작성하여 마크다운 파일로 만들어 놓으면 좋을 듯 합니다.

**Comment by HyunGyu-Lee** [comment]
@hanull 
커밋 형식 따로 정리하여 공유하도록 하겠습니다.

**Comment by HyunGyu-Lee** [comment]
[커밋 메시지 규칙](https://github.com/Team-HST/wwl/blob/master/commitMessages.md) 참고
